### ISSUE TITLE
Окно комментария

### ISSUE THREAD

**Issue by WillWisp** [RuFimFiction/StoriesEP#11]
#5 
Сделать не в окне написание комментария, а прям на странице.
Плавающее окно ответов в комментах. Сделать возможность, чтобы окно ответа фиксировалось внизу окна браузера и при скролинге страницы оставалось на месте (как при ответах на мэйл в  яндексе)

**Comment by tanriol** [comment]
This issue was moved to RuFimFiction/ponyFiction#11
