### ISSUE TITLE
Чтение скрытых рассказов

### ISSUE THREAD

**Issue by EpicMan2** [RuFimFiction/StoriesEP#2]
Рассказы, скрытые модераторами можно легко прочитать путём использования функции преобразования рассказа в формат fb2. Для этого надо воспользоваться #1, выбрать нужный рассказ, и нажать на кнопку преобразования в fb2. Далее текст преобразуется в файл, и его можно будет прочитать.

**Comment by tanriol** [comment]
This issue was moved to RuFimFiction/ponyFiction#2
